baseURL = "https://meik2333.com/"
languageCode = "zh-cn"
title = "MeiK's blog"
theme = "github-style"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "MeiK"
  description = "In solitude, where we are least alone."
  github = "MeiK2333"
  facebook = "MeiK2333"
  twitter = "MeiK2333"
  linkedin = "MeiK2333"
  instagram = "MeiK2333"
  tumblr = "MeiK2333"
  email = "meik2333@gmail.com"
  url = "https://meik2333.com"
  keywords = "blog, google analytics"
  rss = true
  lastmod = true
  favicon = "/images/github-mark.png"
  avatar = "/images/avatar.gif"
  headerIcon = "/images/github-mark-white.png"
  location = "China"
  userStatusEmoji = "😀"
  enableGitalk = true
  enableSearch = true

  [params.gitalk]
    clientID = "Your client ID" # Your client ID
    clientSecret = "Your client secret" # Your client secret
    repo = "LuvSia" # 您的博客的 github 地址 Repository name，例如：xxxx.github.io
    owner = "ventusoon" # 您的 GitHub ID
    admin = "ventusoon" # 您的 GitHub ID
    id = "location.pathname" # 文章页面的链接地址就是 ID
    labels = "gitalk" # Github issue labels. If you used to use Gitment, you can change it
    perPage = 15 # Pagination size, with maximum 100.
    pagerDirection = "last" # Comment sorting direction, available values are 'last' and 'first'.
    createIssueManually = true # 设置为 true，如果是管理员登录，会自动创建 issue，如果是 false，需要管理员手动添加第一个评论 (issue)
    distractionFreeMode = false # Enable hot key (cmd|ctrl + enter) submit comment.
    proxy = "https://cors-anywhere.azm.workers.dev/https://github.com/login/oauth/access_token" # 可以自行添加反向代理
  [[params.links]]
    title = "Link"
    href = "https://github.com/meik2333"
  [[params.links]]
    title = "Link2"
    href = "https://meik2333.com"
    icon = "https://meik2333.com/images/avatar.png"

[params.CDN]
    gitalk_css = "https://data.rdfzsz.eu.org/css/gitalk.css"
    gitalk_min_js = "https://data.rdfzsz.eu.org/js/gitalk.min.js"
    theme_mode_js = "https://data.rdfzsz.eu.org/js/theme-mode.js"
    frameworks_min_css = "https://data.rdfzsz.eu.org/css/frameworks.min.css"
    github_min_css = "https://data.rdfzsz.eu.org/css/github.min.css"
    github_style_css = "https://data.rdfzsz.eu.org/css2/github-style.css"
    github_style_js = "https://data.rdfzsz.eu.org/js2/github-style.js"
    light_css = "https://data.rdfzsz.eu.org/css/light.css"
    dark_css = "https://data.rdfzsz.eu.org/css/dark.css"
    syntax_css = "https://data.rdfzsz.eu.org/css/syntax.css"
    toc_js = "https://data.rdfzsz.eu.org/js2/toc.js"
    toc_css = "https://data.rdfzsz.eu.org/css/toc.css"
    mark_es6_min_js = 'https://data.rdfzsz.eu.org/js/mark.es6.min.js'

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]

[services]
  [services.googleAnalytics]
    ID = "UA-123456-789"
